// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railways.Data;

#nullable disable

namespace Railways.API.Migrations
{
    [DbContext(typeof(RailwaysDbContext))]
    [Migration("20250926112723_Working")]
    partial class Working
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Railways.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PresidentId")
                        .HasColumnType("int");

                    b.Property<int>("StockPriceIndex")
                        .HasColumnType("int");

                    b.Property<int>("TotalShares")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PresidentId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Money = 0,
                            Name = "Expansive",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 2,
                            Money = 0,
                            Name = "Express",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 3,
                            Money = 0,
                            Name = "Suburban",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 4,
                            Money = 0,
                            Name = "Resourceful",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 5,
                            Money = 0,
                            Name = "Eastern Mining",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 6,
                            Money = 0,
                            Name = "Spacious",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 7,
                            Money = 0,
                            Name = "Agricultural",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 8,
                            Money = 0,
                            Name = "Bridging",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 9,
                            Money = 0,
                            Name = "Northern Port",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 10,
                            Money = 0,
                            Name = "Adaptive",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 11,
                            Money = 0,
                            Name = "Overnight",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 12,
                            Money = 0,
                            Name = "Tunneling",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 13,
                            Money = 0,
                            Name = "Manufacturing",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 14,
                            Money = 0,
                            Name = "Twin Cities",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 15,
                            Money = 0,
                            Name = "Circus",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        },
                        new
                        {
                            Id = 16,
                            Money = 0,
                            Name = "Coupling",
                            StockPriceIndex = 0,
                            TotalShares = 5
                        });
                });

            modelBuilder.Entity("Railways.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Money = 0,
                            Username = "Bank"
                        });
                });

            modelBuilder.Entity("Railways.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SharesOwned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Railways.Models.Company", b =>
                {
                    b.HasOne("Railways.Models.Player", "President")
                        .WithMany()
                        .HasForeignKey("PresidentId");

                    b.Navigation("President");
                });

            modelBuilder.Entity("Railways.Models.Stock", b =>
                {
                    b.HasOne("Railways.Models.Company", "Company")
                        .WithMany("Stocks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railways.Models.Player", "Player")
                        .WithMany("Stocks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Railways.Models.Company", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Railways.Models.Player", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
